package fr.banque.entities;
// Generated 22 avr. 2021 à 11:22:31 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "COMPTE", schema = "BDBANQUE")
public class Compte implements java.io.Serializable {

	private BigDecimal idcompte;
	private Client client;
	private String nomcompte;

	public Compte() {
	}

	public Compte(BigDecimal idcompte) {
		this.idcompte = idcompte;
	}

	public Compte(BigDecimal idcompte, Client client, String nomcompte) {
		this.idcompte = idcompte;
		this.client = client;
		this.nomcompte = nomcompte;
	}

	@Id

	@Column(name = "IDCOMPTE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdcompte() {
		return this.idcompte;
	}

	public void setIdcompte(BigDecimal idcompte) {
		this.idcompte = idcompte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCLIENT")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "NOMCOMPTE", length = 20)
	public String getNomcompte() {
		return this.nomcompte;
	}

	public void setNomcompte(String nomcompte) {
		this.nomcompte = nomcompte;
	}

}
