package fr.banque.entities;
// Generated 22 avr. 2021 à 11:20:16 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "CLIENT", schema = "BDBANQUE")
public class Client implements java.io.Serializable {

	private BigDecimal idclient;
	private String nom;
	private String prenom;
	private String adresse;
	private Set<Compte> comptes = new HashSet<Compte>(0);

	public Client() {
	}

	public Client(BigDecimal idclient) {
		this.idclient = idclient;
	}

	public Client(BigDecimal idclient, String nom, String prenom, String adresse, Set<Compte> comptes) {
		this.idclient = idclient;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.comptes = comptes;
	}

	@Id

	@Column(name = "IDCLIENT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdclient() {
		return this.idclient;
	}

	public void setIdclient(BigDecimal idclient) {
		this.idclient = idclient;
	}

	@Column(name = "NOM", length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 20)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "ADRESSE", length = 100)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

}
